### ISSUE TITLE
Suggestion: type to select aspect

### ISSUE THREAD

**Issue by Rseding91** [ythri/tcresearch#15]
First off, I love this tool - it's saved me a ton of time.

But I've got a suggestion; would it be possible to make the "from" and "to" selections respond to keyboard input? So if I type "aer" when the "from" drop down is selected it auto selects aer (or filters or something).

90% of the time I spend doing Thaumcraft research is spent -finding- the 2 aspects in the from and to lists :)

**Comment by ythri** [comment]
Actually, I tried this before, but couldn't get this to work. I will have another look at this issue when I have more time, but I definitely agree: key shortcuts would help immensly.

In the meantime, if anyone with more knowledge of jQuery has any idea (or knows a better list widget that already does this), please tell me. I will leave this issue open for now.

**Comment by MaPePeR** [comment]
@ythri  I implemented this in my fork in the [select2fordropbox-branch](https://github.com/MaPePeR/tcresearch/tree/select2fordropbox).
I changed the library to display the dropdown menu to [Select2](http://ivaynberg.github.io/select2/)

Sadly i can't make a clean pull request, because i based the changes on my other pull request #29. 

Edit: i will just merge all changes into that #29 branch, so you can pull all of it at once, if you want.  If you only want part of its you can always cherry-pick/revert the parts you don't want.

**Comment by ythri** [comment]
The #29 branch has been merged, so typing in the aspect selection works now. Thanks @MaPePeR, and closed!
