### ISSUE TITLE
motus doesn't connect to ordo for the reasearch expertise note

### ISSUE THREAD

**Issue by bryantwilliam** [ythri/tcresearch#30]

**Comment by Smashman** [comment]
Which version are you using?

**Comment by ythri** [comment]
Motus is Aer+Ordo since thaumcraft version 4.1.1. Only before in 4.1.0 it was Aer+Aqua. If you are still using this version, please choose version 4.1.0g at the top of the research page, then all connections will use this old combination. If thats not the problem you had, please clarify (and always specify the version of Thaumcraft you are using please, otherwise we can't really do much).

**Comment by bryantwilliam** [comment]
Oh ok, my bad ;)
