### ISSUE TITLE
Thaumcraft 4.2.0.1 Aspect Combos

### ISSUE THREAD

**Issue by Solidflip** [ythri/tcresearch#31]
Didnt know where to submit this for your amazing site, i have compiled the basic Thaumcraft 4.2.0.1 Aspect combos from my own game and a post on imgur. http://pastebin.com/sa4QHc5M

**Comment by Smashman** [comment]
The combination information is stored in the version_dictionary, here: https://github.com/ythri/tcresearch/blob/gh-pages/version_dictionary.js

The format should be fairly self explanatory. Feel free to open a pull request with your additions.

**Comment by Solidflip** [comment]
Thank you, Is there somewhere that lists the aspect - nicknames? I very well could figure it out but dont want a miscommunication to mess it up.

Also Forbidden Magic v0.52 http://pastebin.com/SPZtXZGe

**Comment by Smashman** [comment]
I presume you're referring to the translation dictionary: https://github.com/ythri/tcresearch/blob/gh-pages/translation_dictionary.js

**Comment by ythri** [comment]
Hey @Solidflip, thanks for your effort. Just two remarks:
1. While checking your list of aspect combinations I saw that in tier 7 you always used perfodio+something, however previously it was instrumentum+something instead. Could you check if this is simply a typing error on your part (which I believe), or something that indeed changed? Thanks.
2. If the tier 7 aspects use instrumentum, then the aspect combinations did not have changed since version 4.1.1.14, which is already available for the tool. As such, it would not be necessary to add a new version to the dictionary, but enough to simply indicate that the combinations for 4.1.1.14 also work for 4.2.*. I will do this once I'm back home, but thanks for the reminder.

**Comment by Solidflip** [comment]
I checked just as i got home and yes i made a typo on perfodio/instrumentum. my bad
